### ISSUE TITLE
Thank you for creating this! Would it be possible to add more styling options and is multitouch supported?

### ISSUE THREAD

**Issue by NateJose123** [ionkorol/korol-joystick#1]
Thank you so much for this! I've been looking all over for this and am so glad I found it. Would there be any way to add more styling options such as opacity etc? Also, is multi-touch supported and how to get values from two instances of the joystick? Thanks!

**Comment by ionkorol** [comment]
Hey Nate, I am glad this helped.
Yes, multi touch is supported. 
To get data from the joysticks please check the onMove, onStart, onStop callback functions. 
Regarding styling I will release an update by tomorrow, where you can add custom styling.
