### ISSUE TITLE
Tried to call timer with ID 412 but no such timer exists.

### ISSUE THREAD

**Issue by Mahmoud-Emad-Tonsy** [ionkorol/korol-joystick#10]
iam using @react-navigation/native in my app and after used joystick don't navigate back and show in console this  WARN  Tried to call timer with ID 412 but no such timer exists. 
and if add  text ot button show me that

ERROR  React Native version mismatch.
JavaScript version: 0.70.14
Native version: 0.72.7

and this is my
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/drawer": "^6.6.6",
    "@react-navigation/native": "^6.1.9",
    "@react-navigation/stack": "^6.3.20",
    "korol-joystick": "^1.7.0",
    "react": "18.2.0",
    "react-native": "0.72.7",
    "react-native-bluetooth-classic": "^1.60.0-rc.30",
    "react-native-device-info": "^10.11.0",
    "react-native-elements": "^3.4.3",
    "react-native-gesture-handler": "^2.13.4",
    "react-native-loading-dots": "^1.4.0",
    "react-native-paper": "^5.11.1",
    "react-native-permissions": "^3.10.1",
    "react-native-reanimated": "^3.5.4",
    "react-native-safe-area-context": "^4.7.4",
    "react-native-screens": "^3.27.0",
    "react-native-select-dropdown": "^3.4.0",
    "react-native-vector-icons": "^10.0.2"
  },

 i will change version it's worked but functionalty of joystick  don't move down

**Comment by Ha0ran2001** [comment]
Did you upgrade the rn version?
