### ISSUE TITLE
Npm install requires the @korsolutions prefix

### ISSUE THREAD

**Issue by dannystaple** [ionkorol/korol-joystick#16]
First - good work on a new release! 

The npm badge on the readme is correct, however, I found that `npm install --save react-native-joystick` got me [something else](https://www.npmjs.com/package/react-native-joystick). 
The README.md should likely be updated to say `npm install --save @korsolutions/react-native-joystick` to get the right one.

**Comment by dannystaple** [comment]
The README should also update the Usage section to match the example.
`import { ReactNativeJoystick } from "@korsolutions/react-native-joystick";`
and 
`<ReactNativeJoystick color="#06b6d4" radius={75} onMove={(data) => console.log(data)} />`

**Comment by Minhaj-Rabby** [comment]
@dannystaple Huge help . many many thanks
